version: 1.0.{build}
branches:
  only:
  - msvc
skip_tags: true
image: Visual Studio 2017
configuration: release
platform: x64
build:
  project: example\ThreadedRenderingGL\ThreadedRenderingGL.vcxproj
  verbosity: detailed
